export type AdminAudioEvent = "click" | "hover" | "success" | "error" | "warning" | "notification" | "new_order" | "cod_alert" | "khalifa_insight" | "daily_closing_ready" | "daily_closing_warning" | "database_health_ok" | "database_health_warning" | "print_ready" | "print_done";
export type AdminAudioSettings = { enabled: boolean; muted: boolean; volume: number; clickSounds: boolean; notificationSounds: boolean; khalifaSounds: boolean; warningSounds: boolean; browserNotifications: boolean; lastEnabledAt?: string };
export type AdminNotificationType = "success" | "warning" | "error" | "info" | "new_order" | "cod" | "print" | "database" | "daily_closing" | "khalifa";
export type AdminNotificationPriority = "low" | "normal" | "high";
export type AdminNotification = { id: string; type: AdminNotificationType; titleAr: string; titleEn: string; bodyAr: string; bodyEn: string; createdAt: string; sectionId?: string; priority?: AdminNotificationPriority; read?: boolean; dedupeKey?: string };
type AddNotificationInput = Omit<AdminNotification, "id" | "createdAt" | "read"> & { id?: string; createdAt?: string; read?: boolean; audioEvent?: AdminAudioEvent; dedupeMs?: number };

export const ADMIN_AUDIO_SETTINGS_KEY = "dn_admin_audio_settings_v1";
export const ADMIN_NOTIFICATIONS_KEY = "dn_admin_notifications_v1";
export const ADMIN_NOTIFICATION_DEDUPE_KEY = "dn_admin_notification_dedupe_v1";

const fallback: AdminAudioSettings = { enabled: false, muted: false, volume: 0.35, clickSounds: true, notificationSounds: true, khalifaSounds: true, warningSounds: true, browserNotifications: false };
let ctx: AudioContext | null = null;
let unlocked = false;
let lastSoundAt = 0;
const hasWindow = () => typeof window !== "undefined";

function safeJson<T>(raw: string | null, fb: T): T { if (!raw) return fb; try { return { ...fb, ...JSON.parse(raw) }; } catch { return fb; } }
export function readAdminAudioSettings(): AdminAudioSettings { if (!hasWindow()) return fallback; return safeJson(window.localStorage.getItem(ADMIN_AUDIO_SETTINGS_KEY), fallback); }
export function writeAdminAudioSettings(settings: AdminAudioSettings) { if (!hasWindow()) return; try { window.localStorage.setItem(ADMIN_AUDIO_SETTINGS_KEY, JSON.stringify(settings)); window.dispatchEvent(new CustomEvent("dn-admin-audio-settings-change", { detail: settings })); } catch { /* noop */ } }
export function resetAdminAudioSettings() { writeAdminAudioSettings(fallback); return fallback; }
function getContext() { if (!hasWindow()) return null; const AudioCtor = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioCtor) return null; ctx ||= new AudioCtor(); return ctx; }
export function unlockAdminAudio() { const audio = getContext(); if (!audio) return; unlocked = true; if (audio.state === "suspended") void audio.resume().catch(() => undefined); }

const profiles: Record<AdminAudioEvent, Array<[number, number, OscillatorType?]>> = { click:[[740,0.055]], hover:[[620,0.045]], success:[[660,0.12],[880,0.16]], error:[[180,0.18,"triangle"]], warning:[[260,0.22,"sine"],[220,0.18,"sine"]], notification:[[920,0.16]], new_order:[[760,0.12],[1040,0.18]], cod_alert:[[520,0.1],[660,0.12],[520,0.1]], khalifa_insight:[[880,0.09,"sine"],[1320,0.18,"sine"]], daily_closing_ready:[[560,0.14],[720,0.18]], daily_closing_warning:[[300,0.22],[260,0.18]], database_health_ok:[[980,0.09],[1240,0.12]], database_health_warning:[[420,0.12,"square"],[320,0.18,"triangle"]], print_ready:[[700,0.08],[940,0.11]], print_done:[[760,0.12],[900,0.1]] };
function allowed(event: AdminAudioEvent, s: AdminAudioSettings) { if (!s.enabled || s.muted) return false; if (hasWindow() && document.hidden && !s.browserNotifications) return false; if ((event === "click" || event === "hover") && !s.clickSounds) return false; if (["notification","new_order","cod_alert","print_ready","print_done","daily_closing_ready"].includes(event) && !s.notificationSounds) return false; if (event === "khalifa_insight" && !s.khalifaSounds) return false; if (["error","warning","daily_closing_warning","database_health_warning"].includes(event) && !s.warningSounds) return false; return true; }
export function playAdminAudioEvent(event: AdminAudioEvent, settings = readAdminAudioSettings()) { if (!allowed(event, settings) || !unlocked) return; const now = Date.now(); if (now - lastSoundAt < 150) return; const audio = getContext(); if (!audio) return; lastSoundAt = now; let offset = 0; for (const [freq, dur, type = "sine"] of profiles[event]) { const osc = audio.createOscillator(); const gain = audio.createGain(); osc.type = type; osc.frequency.value = freq; gain.gain.setValueAtTime(0.0001, audio.currentTime + offset); gain.gain.exponentialRampToValueAtTime(Math.max(0.001, settings.volume * 0.08), audio.currentTime + offset + 0.015); gain.gain.exponentialRampToValueAtTime(0.0001, audio.currentTime + offset + dur); osc.connect(gain); gain.connect(audio.destination); osc.start(audio.currentTime + offset); osc.stop(audio.currentTime + offset + dur + 0.02); offset += dur + 0.025; } }
export function readAdminNotifications(): AdminNotification[] { if (!hasWindow()) return []; const items = safeJson<AdminNotification[]>(window.localStorage.getItem(ADMIN_NOTIFICATIONS_KEY), []); return Array.isArray(items) ? items : []; }
export function writeAdminNotifications(items: AdminNotification[]) { if (!hasWindow()) return; try { window.localStorage.setItem(ADMIN_NOTIFICATIONS_KEY, JSON.stringify(items.slice(0, 30))); window.dispatchEvent(new CustomEvent("dn-admin-notifications-change")); } catch { /* noop */ } }
function readDedupe(): Record<string, number> { return hasWindow() ? safeJson<Record<string, number>>(window.localStorage.getItem(ADMIN_NOTIFICATION_DEDUPE_KEY), {}) : {}; }
function writeDedupe(map: Record<string, number>) { if (!hasWindow()) return; try { window.localStorage.setItem(ADMIN_NOTIFICATION_DEDUPE_KEY, JSON.stringify(map)); } catch { /* noop */ } }
function showBrowserNotification(item: AdminNotification, settings: AdminAudioSettings) { if (!hasWindow() || !settings.browserNotifications || !("Notification" in window) || Notification.permission !== "granted") return; try { new Notification(item.titleEn, { body: item.bodyEn, tag: item.dedupeKey || item.id, silent: true }); } catch { /* noop */ } }
export function addAdminNotification(input: AddNotificationInput): AdminNotification | null { const now = Date.now(); if (input.dedupeKey) { const map = readDedupe(); if (now - (map[input.dedupeKey] || 0) < (input.dedupeMs ?? 300000)) return null; map[input.dedupeKey] = now; writeDedupe(map); } const item: AdminNotification = { id: input.id || `${now}-${Math.random().toString(36).slice(2)}`, type: input.type, titleAr: input.titleAr, titleEn: input.titleEn, bodyAr: input.bodyAr, bodyEn: input.bodyEn, createdAt: input.createdAt || new Date(now).toISOString(), sectionId: input.sectionId, priority: input.priority || "normal", read: false, dedupeKey: input.dedupeKey }; writeAdminNotifications([item, ...readAdminNotifications()]); const settings = readAdminAudioSettings(); showBrowserNotification(item, settings); if (input.audioEvent) playAdminAudioEvent(input.audioEvent, settings); return item; }
export function markAdminNotificationsRead(ids?: string[]) { writeAdminNotifications(readAdminNotifications().map((n) => (!ids || ids.includes(n.id) ? { ...n, read: true } : n))); }
export function clearAdminNotifications() { writeAdminNotifications([]); }
