-- The live Customer Experience test deletes its temporary order, but the new
-- no-CASCADE financial projections intentionally survive order deletion.  Only
-- rows proven by the settlement snapshot to belong to a deleted
-- CUSTOMER_EXPERIENCE_E2E order are eligible here.  Every removed row is copied
-- to a durable audit table first, and the exact reviewed financial snapshot must
-- be restored or the whole migration rolls back.
begin;

create table if not exists public.production_test_dependency_cleanup_audit (
  id bigint generated by default as identity primary key,
  cleanup_version text not null,
  source_table text not null,
  source_row_id text not null,
  order_id uuid,
  resolution_evidence text not null,
  row_before jsonb not null,
  executed_at timestamptz not null default now(),
  unique(cleanup_version, source_table, source_row_id)
);

alter table public.production_test_dependency_cleanup_audit enable row level security;
revoke all on table public.production_test_dependency_cleanup_audit from public, anon, authenticated;
grant all on table public.production_test_dependency_cleanup_audit to service_role;

create temporary table dn_customer_e2e_orphan_orders (
  order_id uuid primary key,
  run_marker text not null
) on commit drop;

create temporary table dn_customer_e2e_cleanup_baseline (
  financial_snapshot jsonb not null
) on commit drop;

insert into dn_customer_e2e_cleanup_baseline(financial_snapshot)
values (public.dn_financial_integrity_snapshot());

insert into dn_customer_e2e_orphan_orders(order_id, run_marker)
select distinct
  public.dn_safe_uuid(s.order_id),
  split_part(s.snapshot ->> 'notes', ':', 2)
from public.order_financial_settlements s
where s.snapshot ->> 'notes' like 'CUSTOMER_EXPERIENCE_E2E:%'
  and public.dn_safe_uuid(s.order_id) is not null
  and not exists (
    select 1 from public.orders o
    where o.id = public.dn_safe_uuid(s.order_id)
  );

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'notifications', n.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(n)
from public.notifications n
join dn_customer_e2e_orphan_orders c
  on public.dn_safe_uuid(n.metadata ->> 'order_id') = c.order_id
on conflict do nothing;
delete from public.notifications n
using dn_customer_e2e_orphan_orders c
where public.dn_safe_uuid(n.metadata ->> 'order_id') = c.order_id;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'outbound_message_logs', m.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(m)
from public.outbound_message_logs m
join dn_customer_e2e_orphan_orders c on m.metadata ->> 'run_id' = c.run_marker
on conflict do nothing;
delete from public.outbound_message_logs m
using dn_customer_e2e_orphan_orders c
where m.metadata ->> 'run_id' = c.run_marker;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'financial_account_entries', a.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(a)
from public.financial_account_entries a
join dn_customer_e2e_orphan_orders c on a.order_id = c.order_id::text
on conflict do nothing;
delete from public.financial_account_entries a
using dn_customer_e2e_orphan_orders c
where a.order_id = c.order_id::text;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'cod_collections', d.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(d)
from public.cod_collections d
join dn_customer_e2e_orphan_orders c on d.order_id = c.order_id
on conflict do nothing;
delete from public.cod_collections d
using dn_customer_e2e_orphan_orders c
where d.order_id = c.order_id;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'merchant_statement_entries', m.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(m)
from public.merchant_statement_entries m
join dn_customer_e2e_orphan_orders c on m.order_id = c.order_id
on conflict do nothing;
delete from public.merchant_statement_entries m
using dn_customer_e2e_orphan_orders c
where m.order_id = c.order_id;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'driver_statement_entries', d.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(d)
from public.driver_statement_entries d
join dn_customer_e2e_orphan_orders c on d.order_id = c.order_id
on conflict do nothing;
delete from public.driver_statement_entries d
using dn_customer_e2e_orphan_orders c
where d.order_id = c.order_id;

insert into public.production_test_dependency_cleanup_audit (
  cleanup_version, source_table, source_row_id, order_id, resolution_evidence, row_before
)
select '20260802034500', 'order_financial_settlements', s.id::text, c.order_id,
  'ORPHANED_CUSTOMER_EXPERIENCE_E2E_DEPENDENCY', to_jsonb(s)
from public.order_financial_settlements s
join dn_customer_e2e_orphan_orders c on s.order_id = c.order_id::text
on conflict do nothing;
delete from public.order_financial_settlements s
using dn_customer_e2e_orphan_orders c
where s.order_id = c.order_id::text;

do $verify$
declare
  v_before jsonb;
  v_current jsonb;
begin
  select financial_snapshot into v_before
  from dn_customer_e2e_cleanup_baseline;
  v_current := public.dn_financial_integrity_snapshot();
  if v_before is null
     or (v_current - 'dependent_tables') is distinct from (v_before - 'dependent_tables')
     or v_current -> 'missing_dependencies' is distinct from v_before -> 'missing_dependencies' then
    raise exception using
      message = 'customer_e2e_cleanup_changed_order_financial_integrity',
      detail = jsonb_build_object(
        'before', v_before,
        'current_after_candidate_cleanup', v_current
      )::text;
  end if;
end;
$verify$;

commit;
