-- =========================================================
-- DAY NIGHT — DRIVER AVATAR + AUTO TRACKING OPERATIONS
-- Additive production migration. No mock locations or Auth password writes.
-- =========================================================

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- 1) Extended driver profile data.
-- -----------------------------------------------------------------------------

alter table public.driver_profiles add column if not exists avatar_path text;
alter table public.driver_profiles add column if not exists avatar_updated_at timestamptz;
alter table public.driver_profiles add column if not exists bio text;
alter table public.driver_profiles add column if not exists work_area text;
alter table public.driver_profiles add column if not exists nationality text;
alter table public.driver_profiles add column if not exists address text;
alter table public.driver_profiles add column if not exists preferred_language text default 'ar';
alter table public.driver_profiles add column if not exists license_expiry date;
alter table public.driver_profiles add column if not exists vehicle_registration_expiry date;

create index if not exists driver_profiles_avatar_path_idx
  on public.driver_profiles(avatar_path)
  where avatar_path is not null;

-- -----------------------------------------------------------------------------
-- 2) Private avatar storage. Signed URLs are generated by the application.
-- -----------------------------------------------------------------------------

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public=false,
  file_size_limit=5242880,
  allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "driver avatars read own or admin" on storage.objects;
create policy "driver avatars read own or admin"
on storage.objects for select to authenticated
using (
  bucket_id='avatars'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.driver_is_admin()
  )
);

drop policy if exists "driver avatars insert own or admin" on storage.objects;
create policy "driver avatars insert own or admin"
on storage.objects for insert to authenticated
with check (
  bucket_id='avatars'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.driver_is_admin()
  )
);

drop policy if exists "driver avatars update own or admin" on storage.objects;
create policy "driver avatars update own or admin"
on storage.objects for update to authenticated
using (
  bucket_id='avatars'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.driver_is_admin()
  )
)
with check (
  bucket_id='avatars'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.driver_is_admin()
  )
);

drop policy if exists "driver avatars delete own or admin" on storage.objects;
create policy "driver avatars delete own or admin"
on storage.objects for delete to authenticated
using (
  bucket_id='avatars'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.driver_is_admin()
  )
);

-- -----------------------------------------------------------------------------
-- 3) Driver self-service profile RPC.
-- -----------------------------------------------------------------------------

create or replace function public.driver_update_own_profile(
  p_phone text default null,
  p_emergency_contact text default null,
  p_avatar_path text default null,
  p_bio text default null,
  p_work_area text default null,
  p_address text default null,
  p_preferred_language text default 'ar'
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $dn$
declare
  v_driver public.driver_profiles%rowtype;
  v_avatar_owner text;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;

  select * into v_driver
  from public.driver_profiles
  where id=auth.uid() or user_id=auth.uid()
  order by case when id=auth.uid() then 0 else 1 end, created_at desc nulls last
  limit 1;

  if not found then raise exception 'driver_setup_required'; end if;
  if v_driver.status::text <> 'active' then raise exception 'driver_inactive'; end if;

  if p_avatar_path is not null then
    v_avatar_owner := split_part(p_avatar_path,'/',1);
    if v_avatar_owner <> auth.uid()::text then
      raise exception 'invalid_avatar_owner';
    end if;
    if not exists(
      select 1 from storage.objects
      where bucket_id='avatars' and name=p_avatar_path
    ) then
      raise exception 'avatar_object_not_found';
    end if;
  end if;

  update public.driver_profiles
  set phone=nullif(btrim(coalesce(p_phone,'')),''),
      emergency_contact=nullif(btrim(coalesce(p_emergency_contact,'')),''),
      avatar_path=coalesce(p_avatar_path,avatar_path),
      avatar_updated_at=case when p_avatar_path is not null then now() else avatar_updated_at end,
      bio=nullif(btrim(coalesce(p_bio,'')),''),
      work_area=nullif(btrim(coalesce(p_work_area,'')),''),
      address=nullif(btrim(coalesce(p_address,'')),''),
      preferred_language=case
        when lower(coalesce(p_preferred_language,'ar')) in ('ar','en')
          then lower(coalesce(p_preferred_language,'ar'))
        else 'ar'
      end,
      updated_at=now()
  where id=v_driver.id
  returning * into v_driver;

  update public.profiles
  set phone=v_driver.phone,updated_at=now()
  where id=auth.uid();

  perform public.driver_audit(
    v_driver.id,
    'driver_self_profile_updated',
    null,
    jsonb_build_object(
      'avatar_updated',p_avatar_path is not null,
      'work_area',v_driver.work_area,
      'preferred_language',v_driver.preferred_language
    )
  );

  return jsonb_build_object('ok',true,'driver',to_jsonb(v_driver));
end
$dn$;

-- -----------------------------------------------------------------------------
-- 4) Expanded admin profile control without overloading the legacy RPC.
-- -----------------------------------------------------------------------------

create or replace function public.admin_update_driver_profile_v2(
  p_driver_id uuid,
  p_full_name text,
  p_phone text default null,
  p_status text default 'active',
  p_shift_status text default 'offline',
  p_vehicle_type text default null,
  p_vehicle_plate text default null,
  p_vehicle_color text default null,
  p_emirate text default null,
  p_license_number text default null,
  p_emergency_contact text default null,
  p_avatar_path text default null,
  p_bio text default null,
  p_work_area text default null,
  p_nationality text default null,
  p_address text default null,
  p_license_expiry text default null,
  p_vehicle_registration_expiry text default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $dn$
declare
  v_driver public.driver_profiles%rowtype;
begin
  if not public.driver_is_admin() then raise exception 'not_authorized'; end if;
  if p_status not in ('active','inactive','suspended') then raise exception 'invalid_driver_status'; end if;
  if p_shift_status not in ('offline','available','busy','paused') then raise exception 'invalid_shift_status'; end if;

  if p_avatar_path is not null and not exists(
    select 1 from storage.objects where bucket_id='avatars' and name=p_avatar_path
  ) then
    raise exception 'avatar_object_not_found';
  end if;

  update public.driver_profiles
  set full_name=coalesce(nullif(btrim(coalesce(p_full_name,'')),''),full_name),
      phone=nullif(btrim(coalesce(p_phone,'')),''),
      status=p_status,
      shift_status=case when p_status='active' then p_shift_status else 'offline' end,
      vehicle_type=nullif(btrim(coalesce(p_vehicle_type,'')),''),
      vehicle_plate=nullif(btrim(coalesce(p_vehicle_plate,'')),''),
      vehicle_color=nullif(btrim(coalesce(p_vehicle_color,'')),''),
      emirate=nullif(btrim(coalesce(p_emirate,'')),''),
      license_number=nullif(btrim(coalesce(p_license_number,'')),''),
      emergency_contact=nullif(btrim(coalesce(p_emergency_contact,'')),''),
      avatar_path=coalesce(p_avatar_path,avatar_path),
      avatar_updated_at=case when p_avatar_path is not null then now() else avatar_updated_at end,
      bio=nullif(btrim(coalesce(p_bio,'')),''),
      work_area=nullif(btrim(coalesce(p_work_area,'')),''),
      nationality=nullif(btrim(coalesce(p_nationality,'')),''),
      address=nullif(btrim(coalesce(p_address,'')),''),
      license_expiry=nullif(btrim(coalesce(p_license_expiry,'')),'')::date,
      vehicle_registration_expiry=nullif(btrim(coalesce(p_vehicle_registration_expiry,'')),'')::date,
      last_status_note=nullif(btrim(coalesce(p_note,'')),''),
      updated_at=now()
  where id=p_driver_id
  returning * into v_driver;

  if not found then raise exception 'driver_not_found'; end if;

  update public.profiles
  set full_name=v_driver.full_name,
      phone=v_driver.phone,
      is_active=(v_driver.status::text='active'),
      updated_at=now()
  where id=coalesce(v_driver.user_id,v_driver.id);

  if v_driver.status::text<>'active' or v_driver.shift_status::text='offline' then
    update public.driver_locations
    set is_online=false,updated_at=now()
    where driver_id=v_driver.id;
  end if;

  perform public.driver_audit(
    v_driver.id,
    'admin_driver_profile_v2_updated',
    null,
    jsonb_build_object(
      'status',v_driver.status::text,
      'shift_status',v_driver.shift_status::text,
      'avatar_updated',p_avatar_path is not null,
      'note',p_note
    )
  );

  return jsonb_build_object('ok',true,'driver',to_jsonb(v_driver));
end
$dn$;

-- -----------------------------------------------------------------------------
-- 5) Grants and verification.
-- -----------------------------------------------------------------------------

grant execute on function public.driver_update_own_profile(text,text,text,text,text,text,text) to authenticated;
grant execute on function public.admin_update_driver_profile_v2(uuid,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text) to authenticated;

create or replace function public.driver_avatar_tracking_health(p_email text default 'driver@daynightae.com')
returns jsonb
language sql
security definer
stable
set search_path=public,auth,storage
as $dn$
  select jsonb_build_object(
    'ok',
      exists(select 1 from auth.users where lower(email)=lower(p_email))
      and exists(
        select 1
        from public.driver_profiles dp
        join auth.users au on au.id=coalesce(dp.user_id,dp.id)
        where lower(au.email)=lower(p_email)
      )
      and to_regprocedure('public.driver_report_location(double precision,double precision,double precision,double precision,double precision,double precision,text,numeric,text)') is not null
      and to_regprocedure('public.driver_update_own_profile(text,text,text,text,text,text,text)') is not null
      and to_regprocedure('public.admin_update_driver_profile_v2(uuid,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text)') is not null,
    'auth_user',exists(select 1 from auth.users where lower(email)=lower(p_email)),
    'driver_profile',exists(
      select 1 from public.driver_profiles dp join auth.users au on au.id=coalesce(dp.user_id,dp.id)
      where lower(au.email)=lower(p_email)
    ),
    'avatar_bucket',exists(select 1 from storage.buckets b where b.id='avatars'),
    'avatar_private',coalesce((select not b.public from storage.buckets b where b.id='avatars'),false),
    'avatar_column',exists(
      select 1 from information_schema.columns
      where table_schema='public' and table_name='driver_profiles' and column_name='avatar_path'
    ),
    'location_rpc',to_regprocedure('public.driver_report_location(double precision,double precision,double precision,double precision,double precision,double precision,text,numeric,text)') is not null,
    'self_profile_rpc',to_regprocedure('public.driver_update_own_profile(text,text,text,text,text,text,text)') is not null,
    'admin_profile_rpc',to_regprocedure('public.admin_update_driver_profile_v2(uuid,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text)') is not null
  )
$dn$;

grant execute on function public.driver_avatar_tracking_health(text) to authenticated;

select public.driver_avatar_tracking_health('driver@daynightae.com');
