export type AdminSectionId =
  | "dashboard" | "live_drivers" | "new_order" | "new_merchant" | "merchants" | "all_orders" | "cancelled" | "review" | "postponed" | "returned" | "customer_experience" | "pickup" | "abu_dhabi" | "external" | "out_scope" | "finance_dashboard" | "driver_statements" | "merchant_statements" | "income" | "cod" | "expenses" | "accounts" | "adjustments" | "audit_log" | "import" | "print" | "reports" | "settings" | "support" | "database_health" | "production_readiness" | "logout";

export type AdminSectionConfig = {
  id: AdminSectionId;
  titleAr: string; titleEn: string; subtitleAr: string; subtitleEn: string;
  icon: string; category: string; dataSource: string;
  kpis: string[]; filters: string[]; inputFields: string[]; actions: string[];
  exportPayload: string; khalifaContext: string;
};

const cfg = (id: AdminSectionId, titleAr: string, titleEn: string, subtitleAr: string, subtitleEn: string, icon: string, category: string, dataSource: string, kpis: string[], filters: string[], inputFields: string[], actions: string[], exportPayload: string, khalifaContext: string): AdminSectionConfig => ({ id, titleAr, titleEn, subtitleAr, subtitleEn, icon, category, dataSource, kpis, filters, inputFields, actions, exportPayload, khalifaContext });

export const adminSectionRegistry: AdminSectionConfig[] = [
  cfg("live_drivers","المندوبون المباشرون","Live Drivers","تتبع مواقع المندوبين الحية وإسناد الطلبات.","Live driver GPS tracking and dispatch visibility.","Truck","dispatch","driver_profiles + driver_locations + orders",["onlineDrivers","idleDrivers","offlineDrivers","activeOrders"],["driver","status","currentOrder"],["refresh"],["openMap","assignDriver"],"drivers live map","live driver tracking and assignment"),
  cfg("dashboard","لوحة التحكم","Dashboard","مؤشرات تشغيل حية وخريطة وقرارات سريعة.","Live operational command with KPIs, map, and quick decisions.","Home","command","orders, merchants, finance_summary",["todayOrders","activeOrders","deliveredOrders","unassignedOrders","delayedOrders","cashPending","incomeToday","netEstimate"],["period","emirate","status"],["periodSelector","emirateFilter","statusFilter","refresh"],["addOrder","addMerchant","reviewPending","openFinance","exportPdf"],"dashboard totals + event feed","live operations summary, delayed, unassigned, cash collection"),
  cfg("new_order","إضافة طلبية جديدة","Add New Order","نموذج طلبية احترافي مع تسعير ورقم تتبع.","Professional order form with pricing and tracking.","PackagePlus","operations","orders, merchants, pricing",["calculatedPrice","merchantStatus","requiredFields","lastSaved"],["merchant","serviceType","paymentType"],["merchant","senderName","senderPhone","pickupEmirate","pickupCity","pickupAddress","receiverName","receiverPhone","deliveryEmirate","deliveryCity","deliveryAddress","packageType","weight","pieces","serviceType","paymentType","cashOnDeliveryAmount","deliveryFee","vatDisplay","customerNotes","adminNotes","priority","pickupDateTime","deliveryDateTime","driver"],["calculatePrice","saveDraft","saveOrder","printLabelPdf"],"saved order label/invoice","new order validation and pricing"),
  cfg("new_merchant","إضافة تاجر","Add Merchant","إنشاء ملف تاجر وموقع استلام واتفاق التحصيل عند التسليم.","Create merchant profile, pickup location, and cash-on-delivery agreement.","UserRoundPlus","operations","merchants, derived orders",["profileCompleteness","cashCollectionEnabled","accountStatus","futureHealth"],["emirate","status"],["companyName","contactPerson","phone","email","businessType","emirate","city","pickupAddress","tradeLicense","trn","cashCollectionEnabled","paymentTerms","pickupTime","agreementNotes","accountStatus","portalAccess"],["saveMerchant"],"merchant profile card","merchant onboarding and future health"),
  cfg("merchants","التجار","Merchants","إدارة التجار وأرصدة التحصيل وصحة الحساب.","Merchant management, cash-on-delivery balances, and account health.","Store","operations","merchants + orders fallback",["totalMerchants","activeMerchants","ordersToday","cashPending","topMerchant"],["search","emirate","status","cashCollectionEnabled"],["searchNamePhoneEmail"],["view","createOrder","statement","deactivate","exportPdf"],"merchant table + health cards","merchant performance, inactive accounts, cash collection"),
  cfg("all_orders","كافة الطلبات","All Orders","جدول الطلبات الكامل مع فلاتر وفرز وإجراءات.","Complete orders table with filters, sorting, and actions.","ClipboardList","orders","orders",["totalOrders","activeOrders","cashTotal","delayedOrders"],["search","status","dateRange","emirate","city","merchant","driver","paymentType","cashOnly","sort"],["bulkSelection"],["view","editStatus","assignDriver","printLabel","exportPdf","exportSelected","markUnderReview","assignSelected"],"visible order rows","all orders, delayed, cash collection and assignments"),
  cfg("cancelled","الطلبات الملغية","Cancelled Orders","تحليل الإلغاءات والأثر المالي.","Cancellation management and financial impact.","X","orders","orders fallback",["cancelledCount","cancellationRate","cancelledValue","topReasons","affectedMerchants"],["reason","merchant","dateRange","refundRequired","cashAffected","city","emirate"],["cancellationReason","refundRequired","cashAffected"],["reopen","archive","exportPdf"],"cancelled rows + reasons","cancellations, affected merchants and value"),
  cfg("review","الطلبات قيد المراجعة","Under Review","قرارات ما قبل التحريك ومشاكل البيانات.","Pre-dispatch decisions and missing data issues.","ShieldCheck","orders","orders fallback",["pendingReview","highPriority","addressProblems","paymentProblems","cashRisk"],["reviewReason","priority","missingData","merchant","paymentIssue","addressIssue"],["reviewReason","priority","missingDataType"],["approve","reject","requestMerchantConfirmation","postpone","assignSupport","exportPdf"],"review decision report","review blockers and cash risk"),
  cfg("postponed","الطلبات المؤجلة","Postponed Orders","جدولة الموجات المؤجلة والمتأخرة.","Manage postponed waves and overdue schedules.","PackageCheck","orders","orders fallback",["postponedToday","dueToday","overduePostponed","nextWave"],["reason","newDeliveryDate","newPickupDate","customerContacted","merchantNotified"],["postponedReason","newDeliveryDate","newPickupDate","customerContacted","merchantNotified"],["reschedule","returnActive","cancel","callCustomerNote","exportPdf"],"postponed report","postponed due dates and customer contact"),
  cfg("returned","الطلبات الراجعة","Returned Orders","متابعة الإرجاع ورسومه وعكس التحصيل.","Returns, return fees, and cash-on-delivery reversal tracking.","RotateCcw","orders","orders fallback",["returnedCount","returnRate","affectedMerchants","cashReversal","repeatAreas"],["returnReason","merchant","dateRange","city","emirate"],["returnReason","returnFee","returnDestination","merchantApproval","itemCondition","returnDate"],["closeReturn","sendMerchant","retryDelivery","markCancelled","exportPdf"],"return report","returns, reversal value and repeat areas"),
  cfg("customer_experience","تجربة العملاء","Customer Experience","التقييمات • الشكاوى • الرسائل","Ratings • Complaints • Messages","MessageSquareWarning","customer_experience","customer_feedback + complaints + outbound_message_logs",["averageRating","totalRatings","openComplaints","unreadMessages"],["status","rating","dateRange","customer","order"],[],["openComplaint","replyToCustomer","changeComplaintStatus","exportReport"],"customer experience report","ratings, complaints, customer messages and service quality"),
  cfg("pickup","الطلبات قيد الإحضار","Pickup Orders","طابور الاستلام وتوزيع المناديب.","Pickup queue and driver workload.","Truck","dispatch","orders fallback",["pickupQueue","assignedPickups","unassignedPickups","driverWorkload","merchantConcentration"],["pickupDate","timeWindow","driver","route","merchant","pickupStatus"],["pickupDate","pickupWindow","pickupDriver","pickupRoute","merchant","pickupStatus"],["assignDriver","markPickedUp","postponePickup","openMap","printManifest","exportPdf"],"pickup manifest","pickup queue and workload"),
  cfg("abu_dhabi","طلبات أبوظبي","Abu Dhabi Orders","عرض إقليمي لأبوظبي ومصفح وخليفة والعين.","Regional view for Abu Dhabi, Mussafah, Khalifa City, and Al Ain.","MapPin","dispatch","orders fallback",["activeAbuDhabi","delayedAbuDhabi","cashAbuDhabi","topArea","routeBurden"],["abuDhabi","mussafah","khalifaCity","mbz","alAin","date","status","merchant"],["regionalDriver"],["focusMap","exportPdf","assignRegionalDriver"],"Abu Dhabi report","Abu Dhabi routes, cash collection and delay"),
  cfg("external","الطلبات الدولية","International Orders","الشحن الدولي والخليجي والجمارك.","International/GCC shipping and customs readiness.","Import","dispatch","orders fallback",["externalOrders","gccOrders","worldwideOrders","pendingCustoms","estimatedRevenue"],["country","serviceType","weight","customsStatus"],["destinationCountry","serviceType","weight","customsNotes","declaredValue","shippingMethod","internationalTracking"],["updateInternationalStatus","exportManifest","printExternalLabel","exportPdf"],"international shipping manifest","international revenue and customs blockers"),
  cfg("out_scope","باقي الإمارات","Other Emirates","طلبيات دبي والشارقة وعجمان وباقي الإمارات خارج أبوظبي.","Dubai, Sharjah, Ajman, and other UAE emirates outside Abu Dhabi.","AlertTriangle","dispatch","orders fallback",["outOfScopeRequests","manualApprovals","approvedManually","rejected"],["emirate","city","date","status","merchant"],["regionalDriver","alternativePrice","adminDecision"],["approveManually","assignRegionalDriver","sendReview","exportPdf"],"other Emirates report","other UAE emirates demand and dispatch decisions"),
  cfg("finance_dashboard","لوحة المالية","Finance Dashboard","محاسبة مشتقة من الطلبات والملخص المالي.","Real/derived accounting dashboard.","BarChart3","finance","finance_summary + orders fallback",["revenue","cashCollected","cashPending","expenses","netEstimate","merchantPayable","driverPayable","averageRevenue","cashRatio","bestArea","weakArea"],["dateRange","period","merchant","driver","emirate","paymentType"],["dateRange","period"],["exportPdf","openIncome","openCashCollection","openExpenses","openStatements"],"finance summary","break-even, cash collection and payables"),
  cfg("driver_statements","كشوفات المناديب","Driver Statements","كشوفات المناديب من الجداول أو الطلبات.","Driver statements from finance tables or safely derived orders.","FileText","finance","driver_settlements fallback orders",["deliveries","assigned","delivered","failedCancelled","cashCollected","earnings","deductions","netPayable"],["driver","dateRange","status","cashOnly","emirate"],["driverSelector","dateRange"],["exportPdf","markCashReconciled","openRoute","printStatement"],"driver statement","driver workload, cash collection and net payable"),
  cfg("merchant_statements","كشوفات التجار","Merchant Statements","أرصدة التجار وصافي المستحق.","Merchant balances and net payable.","ReceiptText","finance","merchant_settlements fallback orders",["merchantOrders","delivered","cancelled","returned","cashTotal","deliveryFees","netBalance"],["merchant","dateRange","paymentStatus","cashOnly","deliveryStatus"],["merchantSelector","dateRange"],["exportPdf","printStatement","openProfile","createOrder"],"merchant statement","merchant cash collection, fees and balance"),
  cfg("income","الدخل","Income","تحليل دخل التوصيل حسب الخدمة والمنطقة.","Delivery income by service and area.","Wallet","finance","orders derived",["deliveryIncome","sameDayIncome","nextDayIncome","externalIncome","incomeByEmirate","incomeByMerchant","dailyTrend"],["dateRange","serviceType","emirate","merchant","paymentMethod"],["dateRange"],["exportReport","comparePeriod","openRows","exportPdf"],"income report","income trends and weak areas"),
  cfg("cod","التحصيل عند التسليم","Cash on Delivery","أرصدة التحصيل عند التسليم للسائقين والتجار والتأخير.","Driver/merchant cash-on-delivery balances and overdue collection.","Wallet","finance","orders derived",["cashTotal","pendingCash","collectedCash","reconciledCash","driverBalances","merchantBalances","overdueCash"],["status","driver","merchant","dateRange","emirate"],["cashStatus"],["markCollected","markReconciled","exportPdf","openDriverStatement"],"cash collection report","pending, collected, reconciled cash collection"),
  cfg("expenses","المصروفات","Expenses","تسجيل واعتماد المصروفات وتأثيرها.","Expense capture, approval, and net impact.","Database","finance","expenses fallback summary",["totalExpenses","byCategory","monthlyExpenses","expenseTrend","netImpact"],["dateRange","category","status","paymentMethod"],["amount","category","paymentMethod","date","notes","attachmentReference","status"],["addExpense","approve","void","exportPdf"],"expenses report","expenses and net operational impact"),
  cfg("accounts","الحسابات","Accounts","مراكز النقد والبنك والتحصيل والمستحقات.","Cash, bank, cash-on-delivery, payables, and operational position.","Database","finance","ledger_entries fallback orders",["cashAccount","bankAccount","cashCollectionAccount","merchantPayable","driverPayable","expenseAccount","netPosition"],["dateRange","accountType"],["accountType"],["exportSummary","openLedger","reconcileCashCollection","exportPdf"],"account summary","account balances from ledger/orders"),
  cfg("adjustments","التسويات","Adjustments","سجل التصحيحات المالية والموافقات.","Finance corrections and approvals register.","RotateCcw","finance","adjustments fallback empty",["register","positiveAdjustments","negativeAdjustments","pendingApprovals"],["type","dateRange","status","merchantDriverOrder"],["adjustmentType","amount","reference","reason","date","notes"],["addAdjustment","approve","void","exportPdf"],"adjustments report","manual corrections and approvals"),
  cfg("audit_log","سجل التدقيق","Audit Log","تدقيق تغييرات المستخدمين والكيانات.","Admin action and entity change audit.","ShieldCheck","system","audit_log fallback order history",["actions","criticalChanges","ordersHistory","latestChanges"],["actionType","dateRange","adminUser","entityType"],["entityType","actionType"],["exportLog","openRelated","filterCritical","exportPdf"],"audit log","critical actions and order history fallback"),
  cfg("import","استيراد الشحنات","Import Shipments","معاينة CSV/XLSX دون ادعاء نجاح غير موجود.","CSV/XLSX preview with clear preview-only mode if backend missing.","Import","tools","local file preview",["importedRows","validRows","invalidRows","duplicates","history"],["merchant","importMode","dryRun"],["uploadCsvXlsx","merchantSelector","importMode","fieldMapping","validationPreview","dryRun"],["downloadTemplate","validateFile","importValidRows","exportErrors"],"import validation errors","import readiness and duplicates"),
  cfg("print","طباعة فواتير","Print Invoices","طابور فواتير وملصقات قابل للطباعة.","Printable invoice and label queue.","Printer","tools","orders",["queue","readyLabels","lastPrinted","previewCount"],["order","merchant","dateRange","language","labelSize","includeQr","includeCashCollection","branding"],["orderSelector","merchantSelector","invoiceLanguage","labelSize","includeQr","includeCashCollection","branding"],["printSelected","exportPdf","printLabels","generateInvoicePack"],"invoice pack","print queue and labels"),
  cfg("reports","التقارير","Reports","تقارير عمليات ومالية وأداء قابلة للتصدير.","Exportable operations, finance, and performance reports.","BarChart3","tools","orders + finance",["generatedRows","operationsSummary","financeSummary","cashCollectionReport","performance"],["reportType","dateRange","emirate","merchant","driver","status","language"],["reportType","dateRange","exportLanguage"],["generateReport","exportPdf","exportCsv","saveFilterLocal"],"selected report","report findings by selected type"),
  cfg("settings","الإعدادات","Settings","إعدادات لوحة الإدارة فقط مع حفظ آمن.","Admin dashboard settings with safe persistence.","Settings","system","localStorage/admin_settings",["theme","density","language","mapMode","thresholds"],["defaultRegion","defaultLanguage"],["avatarOverride","logoReference","themeMode","density","glow","language","mapMode","region","pdfLanguage","visibleKpis","delayedThreshold","cashCollectionThreshold","unassignedThreshold","returnRateWarning","notifications","financePrefs"],["saveSettings","resetSettings"],"settings snapshot","admin preferences and dashboard behavior"),
  cfg("support","الدعم الفني","Technical Support","تشخيص آمن وحالة الاتصال وملاحظات الدعم.","Safe diagnostics, connection status, and support notes.","Headphones","system","safe diagnostics + admin_audit_events",["systemStatus","supabaseStatus","lastSync","openTickets","developerNotes"],["issueType","priority","affectedPage"],["issueType","priority","affectedPage","description","screenshotReference","adminNote"],["createSupportNote","copyDiagnostics","exportPdf"],"support report","system health and common fixes"),
  cfg("database_health","فحص قاعدة البيانات","Database Health","فحص فعلي للجداول والعروض والدوال المطلوبة للإنتاج.","Real verification for production tables, views, and RPCs.","Database","system","Supabase health checks",["totalChecks","working","migrationRequired","permissionIssues","emptyObjects"],["objectType","status"],["rerunChecks","copyReport"],["rerunDatabaseHealth","copyDiagnostics","openFinance","openSettings","exportPdf"],"database health report","Supabase object readiness and migrations"),
  cfg("production_readiness","جاهزية الإنتاج","Production Readiness","بوابة إطلاق نهائية تقيس قاعدة البيانات والمالية والطباعة والتدقيق.","Final launch gate covering database, finance, print, audit, and performance.","ShieldCheck","system","database_health + finance_summary",["overallScore","status","risk","blockers","warnings"],["risk","status"],["rerunReadiness","copyReport"],["rerunReadiness","openDatabaseHealth","openFinance","openSettings","exportPdf"],"production readiness report","launch blockers and release actions"),
  cfg("logout","تسجيل الخروج","Logout","إنهاء جلسة الإدارة.","Sign out of admin session.","LogOut","system","auth",[],[],[],["logout"],"none","session")
];

export const adminSectionById = Object.fromEntries(adminSectionRegistry.map((section) => [section.id, section])) as Record<AdminSectionId, AdminSectionConfig>;
