import { useEffect, useMemo, useState } from "react";
import { FileSpreadsheet, Printer, ReceiptText, ShieldCheck, WalletCards } from "lucide-react";
import AdminPdfExportButton from "./AdminPdfExportButton";
import { approveAdjustment, approveExpense, commitValidImportRows, createAdjustment, createExpense, createImportBatch, createPrintJob, deriveDriverStatementFromOrders, deriveMerchantStatementFromOrders, fetchAdjustments, fetchAdminAuditEvents, fetchDriverStatementEntries, fetchExpenses, fetchMerchantStatementEntries, fetchPrintJobs, markPrintJobPrinted, saveImportPreviewRows, validateImportRows, voidAdjustment, voidExpense, type FinanceRow } from "../../lib/adminData";
import type { Merchant, Order } from "../../types";
import "../../styles/dn-admin-ops-layer.css";

type Props = { id: string; title: string; isArabic: boolean; orders: Order[]; merchants: Merchant[]; onRefresh: () => Promise<void> };
const money = (v: unknown) => `${Number(v || 0).toFixed(2)} AED`;
const cleanDate = (v: unknown) => String(v || new Date().toISOString()).slice(0, 10);
const tracking = (o: any) => o.tracking_number || o.invoice_number || o.coupon_number || o.id || "—";
const inputClass = "rounded-xl border border-white/10 bg-brand-deep/70 px-3 py-2 text-sm font-bold text-white outline-none";
function parseCsv(text: string) { const [head = "", ...lines] = text.split(/\r?\n/).filter(Boolean); const headers = head.split(",").map((h) => h.trim()); return lines.map((line) => Object.fromEntries(line.split(",").map((cell, i) => [headers[i] || `field_${i}`, cell.trim()]))); }
function tablePdf(isArabic: boolean, title: string, rows: FinanceRow[]) { return { language: isArabic ? "ar" as const : "en" as const, sectionTitle: title, filters: isArabic ? "الفلاتر الحالية" : "Current filters", totals: { rows: rows.length }, columns: ["date","tracking","type","debit","credit","balance","notes"].map((key)=>({ key, label: key })), rows: rows.map((r)=>({ date: r.entry_date || cleanDate(r.created_at), tracking: r.tracking_number || r.id || "—", type: r.entry_type || r.action || r.status || "—", debit: money(r.debit), credit: money(r.credit || r.amount), balance: money(r.balance), notes: String(r.notes || r.entity_type || "—") })) }; }
export default function AdminOperationsLayer({ id, title, isArabic, orders, merchants, onRefresh }: Props) {
  const [rows, setRows] = useState<FinanceRow[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [merchantId, setMerchantId] = useState(""); const [driverId, setDriverId] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [codOnly, setCodOnly] = useState(false);
  const [expense, setExpense] = useState({ amount:"", category:"fuel", payment_method:"cash", expense_date:new Date().toISOString().slice(0,10), reference_number:"", notes:"", status:"draft" });
  const [adjustment, setAdjustment] = useState({ adjustment_type:"manual_finance_adjustment", direction:"positive" as "positive"|"negative", amount:"", reason:"", notes:"" });
  const [csvPreview, setCsvPreview] = useState<any[]>([]); const [lastBatchId, setLastBatchId] = useState("");
  const filters = { merchantId, driverId, dateFrom, dateTo };
  async function load() { setBusy(true); setMessage(""); try { let data: FinanceRow[] = []; if (id === "expenses") data = await fetchExpenses(filters); else if (id === "adjustments") data = await fetchAdjustments(filters); else if (id === "audit_log") data = await fetchAdminAuditEvents(filters); else if (id === "print") data = await fetchPrintJobs(filters); else if (id === "driver_statements") { data = await fetchDriverStatementEntries(filters); if (!data.length) data = deriveDriverStatementFromOrders(driverId || undefined, orders, filters); } else if (id === "merchant_statements") { data = await fetchMerchantStatementEntries(filters); if (!data.length) data = deriveMerchantStatementFromOrders(merchantId || undefined, orders, filters); } else if (id === "reports") data = [...await fetchExpenses(filters), ...await fetchAdjustments(filters), ...await fetchPrintJobs(filters)]; setRows(codOnly ? data.filter((r)=>Number(r.debit || r.credit || r.amount || 0) > 0) : data); } catch { setMessage(isArabic ? "تعذر تحميل الجدول المتخصص؛ تم الحفاظ على الواجهة بدون عرض خطأ تقني." : "Specialized table could not be loaded; technical details were hidden."); } finally { setBusy(false); } }
  useEffect(()=>{ void load(); }, [id, orders.length]);
  const totals = useMemo(()=>({ count: rows.length, debit: rows.reduce((s,r)=>s+Number(r.debit||0),0), credit: rows.reduce((s,r)=>s+Number(r.credit||r.amount||0),0), pending: rows.filter((r)=>String(r.status||"").includes("draft") || String(r.status||"").includes("pending") || String(r.status||"").includes("queued")).length }),[rows]);
  async function submitExpense() { if (!expense.amount || Number(expense.amount)<=0 || !expense.category || !expense.expense_date) { setMessage(isArabic ? "المبلغ والتصنيف والتاريخ مطلوبة." : "Amount, category, and date are required."); return; } await createExpense(expense); setMessage(isArabic ? "تم حفظ المصروف كعملية حقيقية." : "Expense saved as a real operation."); await load(); await onRefresh(); }
  async function submitAdjustment() { if (!adjustment.amount || Number(adjustment.amount)<=0 || !adjustment.reason) { setMessage(isArabic ? "المبلغ والسبب مطلوبان." : "Amount and reason are required."); return; } await createAdjustment({ ...adjustment, merchant_id: merchantId || undefined, driver_id: driverId || undefined }); setMessage(isArabic ? "تم إنشاء التسوية." : "Adjustment created."); await load(); }
  async function handleCsv(file: File) { if (!file.name.toLowerCase().endsWith(".csv")) { setMessage(isArabic ? "CSV مدعوم الآن؛ XLSX قيد الانتظار بوضوح." : "CSV is supported now; XLSX remains pending."); return; } const parsed = parseCsv(await file.text()); const validation = validateImportRows(parsed, merchantId || undefined); setCsvPreview(validation); const batch = await createImportBatch({ merchant_id: merchantId || undefined, file_name: file.name, import_mode: "preview", total_rows: validation.length, valid_rows: validation.filter((r)=>r.status==="valid").length, invalid_rows: validation.filter((r)=>r.status==="invalid").length }); setLastBatchId(String(batch.id || "")); await saveImportPreviewRows(String(batch.id), validation); setMessage(isArabic ? "تم حفظ معاينة الاستيراد فقط؛ لم يتم إنشاء طلبات بعد." : "Import preview saved only; no orders were created yet."); }
  async function makePrintJob() { const selected = orders.slice(0, 25).map((o)=>o.id); await createPrintJob({ job_type:"invoice", language:isArabic?"ar":"en", order_ids:selected, merchant_id:merchantId||undefined, filters, pdf_payload: tablePdf(isArabic,title,rows) }); setMessage(isArabic ? "تم إنشاء مهمة طباعة في الطابور." : "Print job queued."); await load(); }
  return <section className="dn-ops-layer" dir={isArabic ? "rtl" : "ltr"}><header><div><span>{isArabic ? "طبقة عمليات حقيقية" : "Real operations layer"}</span><h1>{title}</h1><p>{isArabic ? "كل إجراء يكتب إلى جداول Supabase الجديدة أو يوضح أنه معاينة فقط." : "Actions write to new Supabase tables or are clearly marked preview-only."}</p></div><AdminPdfExportButton payload={tablePdf(isArabic,title,rows)} /></header>
    {message && <div className="dn-ops-message">{message}</div>}
    <div className="dn-ops-filters"><select className={inputClass} value={merchantId} onChange={(e)=>setMerchantId(e.target.value)}><option value="">{isArabic?"كل التجار":"All merchants"}</option>{merchants.map((m)=><option key={m.id} value={m.id}>{m.trade_name}</option>)}</select><input className={inputClass} value={driverId} onChange={(e)=>setDriverId(e.target.value)} placeholder={isArabic?"معرف المندوب":"Driver id"}/><input className={inputClass} type="date" value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)}/><input className={inputClass} type="date" value={dateTo} onChange={(e)=>setDateTo(e.target.value)}/><label className="dn-ops-toggle"><input type="checkbox" checked={codOnly} onChange={(e)=>setCodOnly(e.target.checked)}/> COD</label><button onClick={()=>void load()}>{busy ? (isArabic?"تحميل":"Loading") : (isArabic?"تحديث":"Refresh")}</button></div>
    <div className="dn-ops-kpis"><article><span>{isArabic?"الصفوف":"Rows"}</span><strong>{totals.count}</strong></article><article><span>{isArabic?"مدين":"Debit"}</span><strong>{money(totals.debit)}</strong></article><article><span>{isArabic?"دائن/مبلغ":"Credit/Amount"}</span><strong>{money(totals.credit)}</strong></article><article><span>{isArabic?"بانتظار إجراء":"Pending"}</span><strong>{totals.pending}</strong></article></div>
    {id === "expenses" && <div className="dn-ops-form"><input className={inputClass} type="number" placeholder="Amount" value={expense.amount} onChange={(e)=>setExpense({...expense,amount:e.target.value})}/><select className={inputClass} value={expense.category} onChange={(e)=>setExpense({...expense,category:e.target.value})}>{["fuel","driver","maintenance","tolls","office","software","marketing","other"].map(c=><option key={c}>{c}</option>)}</select><input className={inputClass} type="date" value={expense.expense_date} onChange={(e)=>setExpense({...expense,expense_date:e.target.value})}/><input className={inputClass} placeholder="Reference" value={expense.reference_number} onChange={(e)=>setExpense({...expense,reference_number:e.target.value})}/><input className={inputClass} placeholder="Notes" value={expense.notes} onChange={(e)=>setExpense({...expense,notes:e.target.value})}/><button onClick={()=>void submitExpense()}>{isArabic?"إضافة مصروف":"Add expense"}</button></div>}
    {id === "adjustments" && <div className="dn-ops-form"><select className={inputClass} value={adjustment.adjustment_type} onChange={(e)=>setAdjustment({...adjustment,adjustment_type:e.target.value})}>{["cod_correction","merchant_correction","driver_deduction","refund","manual_finance_adjustment"].map(c=><option key={c}>{c}</option>)}</select><select className={inputClass} value={adjustment.direction} onChange={(e)=>setAdjustment({...adjustment,direction:e.target.value as any})}><option>positive</option><option>negative</option></select><input className={inputClass} type="number" placeholder="Amount" value={adjustment.amount} onChange={(e)=>setAdjustment({...adjustment,amount:e.target.value})}/><input className={inputClass} placeholder="Reason" value={adjustment.reason} onChange={(e)=>setAdjustment({...adjustment,reason:e.target.value})}/><input className={inputClass} placeholder="Notes" value={adjustment.notes} onChange={(e)=>setAdjustment({...adjustment,notes:e.target.value})}/><button onClick={()=>void submitAdjustment()}>{isArabic?"إنشاء تسوية":"Create adjustment"}</button></div>}
    {id === "import" && <div className="dn-ops-form"><input className={inputClass} type="file" accept=".csv,.xlsx" onChange={(e)=>e.target.files?.[0] && void handleCsv(e.target.files[0])}/><button disabled={!lastBatchId} onClick={async()=>{ const r=await commitValidImportRows(lastBatchId); setMessage(r.message); }}>{isArabic?"اعتماد الصفوف الصحيحة":"Commit valid rows"}</button><span>{isArabic?"وضع المعاينة فقط واضح حتى إنشاء الطلبات فعلياً.":"Preview-only mode is explicit until orders are actually created."}</span></div>}
    {id === "print" && <div className="dn-ops-form"><button onClick={()=>void makePrintJob()}>{isArabic?"إنشاء مهمة طباعة":"Create print job"}</button><span>{isArabic?"تستخدم حمولة PDF الحالية وقائمة الطلبات المفلترة.":"Uses current PDF payload and filtered order list."}</span></div>}
    <div className="dn-ops-actions"><button onClick={()=>void makePrintJob()}><Printer />{isArabic?"طباعة/طابور":"Print/queue"}</button><button onClick={()=>rows[0]?.id && void (id==="expenses"?approveExpense(String(rows[0].id)):approveAdjustment(String(rows[0].id))).then(load)}><ShieldCheck />{isArabic?"اعتماد أول صف":"Approve first"}</button><button onClick={()=>rows[0]?.id && void (id==="expenses"?voidExpense(String(rows[0].id),"Voided from admin"):voidAdjustment(String(rows[0].id),"Voided from admin")).then(load)}><WalletCards />{isArabic?"إلغاء أول صف":"Void first"}</button></div>
    <div className="dn-ops-table"><table><thead><tr><th>{isArabic?"التاريخ":"Date"}</th><th>{isArabic?"التتبع/الكيان":"Tracking/entity"}</th><th>{isArabic?"النوع":"Type"}</th><th>{isArabic?"مدين":"Debit"}</th><th>{isArabic?"دائن":"Credit"}</th><th>{isArabic?"الرصيد":"Balance"}</th><th>{isArabic?"ملاحظات":"Notes"}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id||i)}><td>{String(r.entry_date || cleanDate(r.created_at))}</td><td>{String(r.tracking_number || r.entity_id || r.id || "—")}</td><td>{String(r.entry_type || r.adjustment_type || r.category || r.action || r.job_type || r.status || "—")}</td><td>{money(r.debit)}</td><td>{money(r.credit || r.amount)}</td><td>{money(r.balance)}</td><td>{String(r.notes || r.metadata || r.status || "—").slice(0,80)}</td></tr>)}</tbody></table>{!rows.length && <div className="dn-ops-empty"><FileSpreadsheet />{isArabic?"لا توجد صفوف؛ سيتم الاشتقاق من الطلبات حيث ينطبق ذلك.":"No rows; order-derived fallback appears where applicable."}</div>}</div>
    {csvPreview.length > 0 && <div className="dn-ops-preview"><ReceiptText /> {isArabic?"معاينة الاستيراد":"Import preview"}: {csvPreview.filter((r)=>r.status==="valid").length} valid / {csvPreview.length} total</div>}
  </section>;
}
