import { X } from "lucide-react";
import type { Merchant, Order, OrderStatusHistoryItem } from "../../types";
import { statusLabel, fieldLabel, actionLabel } from "../../data/adminTranslations";

type Props = { order: Order | null; merchants: Merchant[]; isArabic: boolean; onClose: () => void; onStatus: (order: Order) => void; onAssign: (order: Order) => void; onMerchant: (merchant: Merchant) => void; onPreview: (message: string) => void };
type ExtraOrder = Order & { pickup_city?: string; pickup_address?: string; delivery_city?: string; delivery_address?: string; assigned_driver_name?: string; driver_id?: string; admin_notes?: string };
const val = (v: unknown) => String(v ?? "").trim() || "—";
const money = (v: unknown) => `${Number(v || 0).toFixed(2)} AED`;
const extra = (o: Order) => o as ExtraOrder;
const ref = (o: Order) => o.tracking_number || o.invoice_number || o.coupon_number || o.id || "—";
const merchantName = (m?: Merchant) => m?.trade_name || m?.owner_name || m?.merchant_code || "—";
export default function AdminOrderDetailsDrawer({ order, merchants, isArabic, onClose, onStatus, onAssign, onMerchant, onPreview }: Props) {
  if (!order) return null;
  const x = extra(order); const merchant = merchants.find((m)=>m.id === order.merchant_id || m.trade_name === order.merchant_name);
  const timeline = (order.status_history || []) as OrderStatusHistoryItem[];
  const rows = [[fieldLabel("status",isArabic), statusLabel(order.status,isArabic)],[fieldLabel("merchant",isArabic), merchantName(merchant) || order.merchant_name],[isArabic?"المرسل":"Sender", order.sender_name],[isArabic?"المستلم":"Receiver", order.receiver_name],[isArabic?"هاتف المرسل":"Sender phone", order.sender_phone],[isArabic?"هاتف المستلم":"Receiver phone", order.receiver_phone],[isArabic?"مدينة الإحضار":"Pickup city", order.sender_city || x.pickup_city],[isArabic?"عنوان الإحضار":"Pickup address", order.sender_address || x.pickup_address],[isArabic?"مدينة التسليم":"Delivery city", order.receiver_city || x.delivery_city],[isArabic?"عنوان التسليم":"Delivery address", order.receiver_address || x.delivery_address],[fieldLabel("serviceType",isArabic), order.service_type],[isArabic?"قيمة COD":"COD amount", money(order.cod_amount)],[isArabic?"رسوم التوصيل":"Delivery fee", money(order.delivery_price || order.price)],[isArabic?"المندوب":"Driver", x.assigned_driver_name || order.driver_name || x.driver_id],[isArabic?"ملاحظات":"Notes", order.notes || x.admin_notes],[isArabic?"تاريخ الإنشاء":"Created", order.created_at],[isArabic?"آخر تحديث":"Last update", order.updated_at]];
  return <aside className="dn-admin-drawer" dir={isArabic?"rtl":"ltr"}><header><div><span>{isArabic ? "تفاصيل الطلب" : "Order details"}</span><strong>{ref(order)}</strong></div><button type="button" onClick={onClose}><X className="h-4 w-4" /></button></header><section className="dn-admin-drawer-grid">{rows.map(([label,value])=><article key={label}><span>{label}</span><strong>{val(value)}</strong></article>)}</section><section><h3>{isArabic ? "ملخص المسار" : "Route summary"}</h3><p>{val(order.sender_city || x.pickup_city)} → {val(order.receiver_city || x.delivery_city || order.destination_country)}</p></section><section><h3>{isArabic ? "سجل الحالة" : "Status timeline"}</h3>{timeline.length ? <ol>{timeline.slice(0,8).map((item,index)=><li key={`${item.status}-${index}`}>{statusLabel(item.status,isArabic)} · {val(item.created_at || item.updated_at || item.timestamp || item.date)} · {val(item.note)}</li>)}</ol> : <p>{isArabic ? "لا يوجد سجل حالة محفوظ لهذا الطلب." : "No saved status timeline for this order."}</p>}</section><footer><button type="button" onClick={()=>onStatus(order)}>{isArabic?"تحديث الحالة":"Update status"}</button><button type="button" onClick={()=>onAssign(order)}>{actionLabel("assignDriver",isArabic)}</button><button type="button" onClick={()=>onStatus({ ...order, status: "under_review" })}>{isArabic?"وضع تحت المراجعة":"Mark under review"}</button><button type="button" onClick={()=>onStatus({ ...order, status: "postponed" })}>{isArabic?"تأجيل":"Postpone"}</button><button type="button" onClick={()=>onStatus({ ...order, status: "cancelled" })}>{isArabic?"إلغاء":"Cancel"}</button><button type="button" onClick={()=>onStatus({ ...order, status: "returned" })}>{isArabic?"إرجاع":"Return"}</button><button type="button" onClick={()=>onPreview(isArabic?"معاينة طباعة البوليصة متاحة عبر طابور الطباعة.":"Print label preview is available through the print queue.")}>{isArabic?"طباعة بوليصة":"Print label"}</button><button type="button" onClick={()=>onPreview(isArabic?"تصدير PDF للطلب قيد المعاينة.":"Order PDF export is in preview.")}>{actionLabel("exportPdf",isArabic)}</button>{merchant && <button type="button" onClick={()=>onMerchant(merchant)}>{isArabic?"فتح التاجر":"Open merchant"}</button>}</footer></aside>;
}
