import React from "react";
import { Bell, ChevronDown, Grid2X2, Headphones, Home, MapPin, MessageCircle, Star, Truck } from "lucide-react";

const LOGO_SRC = "/assets/daynight/admin-auth-v3/logo-glass.png";
const KHALIFA_SRC = "/assets/daynight/admin-auth-v3/khalifa-card-reference.png";
const MAP_SRC = "/assets/daynight/admin-auth-v3/admin-map.png";
const card: React.CSSProperties = { border: "1px solid rgba(116,177,255,.32)", borderRadius: 28, background: "linear-gradient(180deg,rgba(8,31,76,.72),rgba(3,14,34,.86))", padding: 20, color: "#fff" };

function LeftPanel() { return <aside style={card}><div style={{ display: "grid", gridTemplateColumns: "auto 1fr auto auto", gap: 10, alignItems: "center" }}><img src={KHALIFA_SRC} alt="أبو خليفة" style={{ width: 56, height: 56, borderRadius: 999, objectFit: "cover" }} /><div><strong>أبو خليفة</strong><br /><span style={{ color: "#f4c24f" }}>مدير النظام</span></div><ChevronDown /><Bell /></div><section style={{ marginTop: 18, textAlign: "center" }}><div style={{ display: "inline-flex", padding: "10px 18px", borderRadius: 999, color: "#061224", background: "#f4c24f", fontWeight: 1000 }}>أهلاً يا أبو خليفة</div><img src={KHALIFA_SRC} alt="خليفة" style={{ display: "block", maxWidth: "100%", height: 250, objectFit: "contain", margin: "12px auto" }} /><h2 style={{ color: "#f4c24f" }}>خليفة</h2><p>مساعدك الذكي</p><span>تحت أمرك يا أبو خليفة، كيف أقدر أساعدك اليوم؟</span><br /><button type="button" style={{ marginTop: 14, padding: "12px 20px", borderRadius: 16, background: "#f4c24f", color: "#071a33", fontWeight: 1000 }}>اسألني أي شيء</button></section><section style={{ marginTop: 18, textAlign: "center" }}><Headphones /><h3>مساعدة</h3><strong>سيظهر المحتوى هنا</strong></section></aside>; }
function HomeMap() { return <section style={{ ...card, position: "relative", minHeight: 420, overflow: "hidden" }}><div style={{ position: "relative", zIndex: 3, display: "flex", justifyContent: "space-between" }}><div><h2>تتبع الشحنة</h2><p>تابع شحنتك لحظة بلحظة</p></div><Truck /></div><img src={MAP_SRC} alt="خريطة تتبع الشحنة" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", opacity: .55 }} /><div style={{ position: "absolute", right: "9%", bottom: "21%", zIndex: 4, padding: 12, borderRadius: 16, background: "rgba(2,11,30,.75)" }}><strong>نقطة الاستلام</strong><br /><span>تم استلام الشحنة</span><MapPin /></div><div style={{ position: "absolute", left: "43%", bottom: "29%", zIndex: 4, padding: 12, borderRadius: 16, background: "rgba(2,11,30,.75)" }}><strong>جاري التوصيل</strong><br /><span>الشحنة في الطريق إليك</span><Star /></div><div style={{ position: "absolute", left: "8%", bottom: "34%", zIndex: 4, padding: 12, borderRadius: 16, background: "rgba(2,11,30,.75)" }}><strong>نقطة التسليم</strong><br /><span>الشحنة في طريقها إليك</span><Star /></div></section>; }
function Sidebar() { const items = ["لوحة التحكم", "إضافة طلب جديد", "إضافة تاجر", "التجار", "كافة الطلبات", "الطلبات الملغية", "الطلبات قيد المراجعة", "الطلبات المؤجلة", "الطلبات الراجعة", "طلبات أبوظبي", "التقارير", "الإعدادات", "الدعم الفني"]; return <aside style={card}><img src={LOGO_SRC} alt="DAY NIGHT" style={{ width: 116, height: 116, display: "block", margin: "0 auto 20px", objectFit: "contain" }} /><nav style={{ display: "grid", gap: 7 }}>{items.map((item, index) => <button type="button" key={item} style={{ display: "flex", alignItems: "center", gap: 10, minHeight: 43, borderRadius: 14, color: index === 0 ? "#071a33" : "#fff", background: index === 0 ? "#f4c24f" : "rgba(8,33,76,.46)", fontWeight: 900 }}><Home /><span>{item}</span></button>)}</nav></aside>; }
export default function AdminDashboardHomeV3() { return <section dir="rtl" style={{ width: "100%", color: "#fff" }}><div style={{ display: "grid", gridTemplateColumns: "280px 1fr 280px", gap: 24 }}><LeftPanel /><main style={{ ...card, display: "grid", gap: 22 }}><header style={{ display: "flex", justifyContent: "space-between" }}><div><h1>مرحباً بك في مركز القيادة</h1><p style={{ color: "#f4c24f" }}>تحكم كامل بشحناتك من نقطة إلى نقطة</p></div><Grid2X2 /></header><HomeMap /><section style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16 }}>{["آخر التحديثات", "معلومات الشحنة", "تفاصيل الشحنة", "مساعدة سريعة"].map((title) => <article style={card} key={title}><MessageCircle /><h3>{title}</h3><strong>لا توجد بيانات حالياً</strong><br /><span>سيظهر المحتوى هنا</span></article>)}</section></main><Sidebar /></div></section>; }
