import { useState, type FormEvent } from "react";
import { X } from "lucide-react";
import type { Order } from "../../types";
import { createAdminAuditEvent } from "../../lib/adminData";

type Props = { order: Order | null; isArabic: boolean; open: boolean; onClose: () => void; onSaved?: () => Promise<void> | void };
const ref = (order: Order) => order.tracking_number || order.invoice_number || order.coupon_number || order.id || "—";
export default function AdminDriverAssignmentModal({ order, isArabic, open, onClose, onSaved }: Props) {
  const [driver, setDriver] = useState(""); const [phone, setPhone] = useState(""); const [region, setRegion] = useState(""); const [priority, setPriority] = useState("normal"); const [note, setNote] = useState(""); const [message, setMessage] = useState("");
  if (!open || !order) return null;
  const currentOrder = order;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!driver.trim()) { setMessage(isArabic ? "اسم/معرف المندوب مطلوب." : "Driver name/id is required."); return; } if (!currentOrder.id) { setMessage(isArabic ? "لا يوجد معرف طلب صالح؛ التعيين تجريبي فقط." : "No valid order id; assignment preview only."); return; } try { await createAdminAuditEvent({ entity_type: "order", entity_id: currentOrder.id, action: "driver_assignment_preview", metadata: { driver, phone, region, priority, note } }); setMessage(isArabic ? "تم تسجيل معاينة التعيين في التدقيق. تحديث الطلب الفعلي يحتاج حقل تعيين مدعوماً في قاعدة البيانات." : "Assignment preview was audited. Real order assignment needs a supported DB assignment field."); await onSaved?.(); } catch { setMessage(isArabic ? "التعيين تجريبي/غير متصل؛ لم يتم ادعاء نجاح قاعدة البيانات." : "Assignment is preview/offline; no fake DB success was claimed."); } }
  return <div className="dn-admin-modal-backdrop" role="dialog" aria-modal="true"><form className="dn-admin-action-modal" onSubmit={submit}><header><div><span>{isArabic ? "تعيين مندوب" : "Assign driver"}</span><strong>{ref(currentOrder)}</strong></div><button type="button" onClick={onClose}><X className="h-4 w-4" /></button></header><label>{isArabic ? "المندوب" : "Driver"}<input value={driver} onChange={(e)=>setDriver(e.target.value)} placeholder={isArabic ? "اسم أو معرف المندوب" : "Driver name or id"} /></label><label>{isArabic ? "هاتف المندوب" : "Driver phone"}<input value={phone} onChange={(e)=>setPhone(e.target.value)} /></label><label>{isArabic ? "المنطقة/الإمارة" : "Region/emirate"}<input value={region} onChange={(e)=>setRegion(e.target.value)} placeholder={currentOrder.receiver_city || currentOrder.sender_city || ""} /></label><label>{isArabic ? "الأولوية" : "Priority"}<select value={priority} onChange={(e)=>setPriority(e.target.value)}><option value="normal">{isArabic ? "عادي" : "Normal"}</option><option value="high">{isArabic ? "عالي" : "High"}</option><option value="urgent">{isArabic ? "عاجل" : "Urgent"}</option></select></label><label>{isArabic ? "ملاحظة التعيين" : "Assignment note"}<textarea value={note} onChange={(e)=>setNote(e.target.value)} /></label>{message && <p className="dn-admin-modal-message">{message}</p>}<footer><button type="button" onClick={onClose}>{isArabic ? "إغلاق" : "Close"}</button><button type="submit">{isArabic ? "حفظ التعيين" : "Save assignment"}</button></footer></form></div>;
}
