import { useEffect, useMemo, useState } from "react";
import { Database, FileText, Printer, RefreshCw } from "lucide-react";
import type { Merchant, Order } from "../../types";
import { commitValidImportRows, createImportBatch, saveImportPreviewRows, validateImportRows, type FinanceRow } from "../../lib/adminData";
import { fetchProductionRows, productionTableForSection, rowBalance, rowCredit, rowDate, rowDebit, rowNotes, rowReference, rowType, summarizeRows, type AdminProductionSource } from "../../lib/adminProductionData";
import { fieldLabel } from "../../data/adminTranslations";
import AdminPdfExportButton from "./AdminPdfExportButton";
import AdminFinanceOperationsCenter from "./AdminFinanceOperationsCenter";
import "../../styles/dn-admin-ops-layer.css";

type FinanceArea = "finance_dashboard" | "driver_statements" | "merchant_statements" | "income" | "cod" | "expenses" | "accounts" | "adjustments" | "audit_log";
type Props = { id: string; title: string; isArabic: boolean; orders: Order[]; merchants: Merchant[]; onRefresh: () => Promise<void>; };
const financeSections: FinanceArea[] = ["finance_dashboard", "driver_statements", "merchant_statements", "income", "cod", "expenses", "accounts", "adjustments", "audit_log"];
const isFinanceSection = (id: string): id is FinanceArea => financeSections.includes(id as FinanceArea);
const clean = (value: unknown) => String(value ?? "").trim();
const money = (value: unknown, isArabic: boolean) => isArabic ? `${Number(value || 0).toFixed(2)} درهم` : `${Number(value || 0).toFixed(2)} AED`;
const hasArabic = (value: string) => /[\u0600-\u06FF]/.test(value);
const labels: Record<string, { ar: string; en: string }> = { date: { ar: "التاريخ", en: "Date" }, tracking: { ar: "التتبع/الكيان", en: "Tracking/entity" }, type: { ar: "النوع", en: "Type" }, debit: { ar: "مدين", en: "Debit" }, credit: { ar: "دائن", en: "Credit" }, balance: { ar: "الرصيد", en: "Balance" }, notes: { ar: "ملاحظات", en: "Notes" }, rows: { ar: "الصفوف", en: "Rows" }, pending: { ar: "بانتظار إجراء", en: "Pending" }, credit_amount: { ar: "دائن/مبلغ", en: "Credit/Amount" }, organized_layer: { ar: "طبقة إنتاج منظمة", en: "Organized production layer" }, organized_text: { ar: "هذا القسم يستخدم الجداول الفعلية عند توفرها، ولا يعرض بيانات وهمية.", en: "This section uses real tables when available and never shows fake data." }, all_merchants: { ar: "كل التجار", en: "All merchants" }, refresh: { ar: "تحديث", en: "Refresh" }, loading: { ar: "تحميل", en: "Loading" }, print: { ar: "طباعة", en: "Print" }, no_rows: { ar: "لا توجد صفوف محفوظة لهذا القسم بعد.", en: "No saved rows exist for this section yet." }, import_commit: { ar: "اعتماد صفوف CSV الصالحة", en: "Commit valid CSV rows" }, preview_saved: { ar: "صفوف معاينة محفوظة", en: "Preview rows saved" }, source: { ar: "مصدر البيانات", en: "Data source" }, db_source: { ar: "مصدر فعلي من قاعدة البيانات", en: "Real database source" }, ready_source: { ar: "جاهز للتفعيل", en: "Ready to activate" }, delivery_income: { ar: "دخل التوصيل", en: "Delivery income" }, order_cod: { ar: "COD الطلب", en: "Order COD" }, order_cancelled: { ar: "طلب ملغي", en: "Order cancelled" }, order_canceled: { ar: "طلب ملغي", en: "Order canceled" }, order_delivered: { ar: "طلب تم تسليمه", en: "Order delivered" }, order_pending: { ar: "طلب قيد الانتظار", en: "Order pending" }, order_completed: { ar: "طلب مكتمل", en: "Order completed" }, draft: { ar: "مسودة", en: "Draft" }, approved: { ar: "معتمد", en: "Approved" }, void: { ar: "ملغي", en: "Void" }, cash: { ar: "نقدي", en: "Cash" }, fuel: { ar: "وقود", en: "Fuel" }, valid: { ar: "صحيح", en: "Valid" }, invalid: { ar: "غير صحيح", en: "Invalid" } };
const t = (key: string, isArabic: boolean) => isArabic ? labels[key]?.ar || key : labels[key]?.en || key;
function valueLabel(value: unknown, isArabic: boolean) { const raw = clean(value); const key = raw.toLowerCase().replace(/[\s-]+/g, "_"); const pair = labels[key]; if (pair) return isArabic ? pair.ar : pair.en; if (!isArabic) return raw.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) || "—"; return hasArabic(raw) ? raw : "غير محدد"; }
function noteLabel(value: unknown, isArabic: boolean) { const raw = clean(value); if (!raw || raw === "—") return "—"; const loaded = raw.match(/^Order (.+) loaded from production orders\.?$/i) || raw.match(/^order_loaded:(.+)$/); if (loaded) return isArabic ? `تم تحميل الطلب ${loaded[1]} من الطلبات الفعلية.` : `Order ${loaded[1]} loaded from production orders.`; const pair = labels[raw.toLowerCase().replace(/[\s-]+/g, "_")]; if (pair) return isArabic ? pair.ar : pair.en; if (!isArabic) return raw; return hasArabic(raw) ? raw : "ملاحظة محفوظة في السجل"; }
function parseCsv(text: string): Record<string, string>[] { const [head = "", ...lines] = text.split(/\r?\n/).filter(Boolean); const headers = head.split(",").map((header) => header.trim()); if (!headers.length) return []; return lines.map((line) => Object.fromEntries(line.split(",").map((cell, index) => [headers[index] || `field_${index}`, cell.trim()]))); }
function sourceText(source: AdminProductionSource, isArabic: boolean, table: string) { if (source === "db") return isArabic ? t("db_source", true) : `${t("db_source", false)}: ${table}`; return isArabic ? t("ready_source", true) : `${t("ready_source", false)}: ${table}`; }
function tablePdf(isArabic: boolean, title: string, source: string, rows: FinanceRow[]) { return { language: isArabic ? ("ar" as const) : ("en" as const), sectionTitle: title, filters: `${t("source", isArabic)}: ${source}`, totals: { rows: rows.length, debit: money(rows.reduce((sum, row) => sum + rowDebit(row), 0), isArabic), credit: money(rows.reduce((sum, row) => sum + rowCredit(row), 0), isArabic), balance: money(rows.reduce((sum, row) => sum + rowBalance(row), 0), isArabic) }, columns: ["date", "tracking", "type", "debit", "credit", "balance", "notes"].map((key) => ({ key, label: fieldLabel(key, isArabic) || t(key, isArabic) })), rows: rows.map((row) => ({ date: rowDate(row), tracking: rowReference(row), type: valueLabel(rowType(row), isArabic), debit: money(rowDebit(row), isArabic), credit: money(rowCredit(row), isArabic), balance: money(rowBalance(row), isArabic), notes: noteLabel(rowNotes(row), isArabic) })) }; }
export default function AdminOperationsLayer({ id, title, isArabic, orders, merchants, onRefresh }: Props) {
  const [financeSection, setFinanceSection] = useState<FinanceArea>(isFinanceSection(id) ? id : "finance_dashboard"); const [rows, setRows] = useState<FinanceRow[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [source, setSource] = useState<AdminProductionSource>("unavailable"); const [tableName, setTableName] = useState(productionTableForSection(id).table); const [merchantId, setMerchantId] = useState(""); const [importPreview, setImportPreview] = useState<ReturnType<typeof validateImportRows>>([]); const [lastBatchId, setLastBatchId] = useState("");
  async function load() { if (isFinanceSection(id)) return; setBusy(true); setMessage(""); try { const result = await fetchProductionRows(id, merchantId ? { merchantId } : {}); const normalized = result.rows.map((row) => ({ ...row, debit: rowDebit(row), credit: rowCredit(row), balance: rowBalance(row) })); setRows(normalized); setSource(result.source); setTableName(result.table); setMessage(result.source === "db" ? (isArabic ? "تم تحميل الصفوف من قاعدة البيانات." : "Rows loaded from database.") : (isArabic ? "القسم جاهز؛ طبّق migration إذا كان الجدول بلا صفوف." : "Section is ready; apply the migration if the table has no rows.")); } catch (error) { console.warn("Admin operation load failed:", error); setRows([]); setSource("unavailable"); setMessage(isArabic ? "القسم جاهز للتفعيل ولا يعرض صفوفاً وهمية." : "Section is ready to activate and does not show fake rows."); } finally { setBusy(false); } }
  useEffect(() => { if (isFinanceSection(id)) setFinanceSection(id); void load(); }, [id, merchantId]);
  const totals = useMemo(() => summarizeRows(rows), [rows]); const dataSourceText = sourceText(source, isArabic, tableName);
  async function handleCsv(file: File) { if (!file.name.toLowerCase().endsWith(".csv")) { setMessage(isArabic ? "CSV مدعوم الآن. لا يتم إنشاء صفوف وهمية من XLSX." : "CSV is supported now. No fake XLSX rows are created."); return; } setBusy(true); try { const validation = validateImportRows(parseCsv(await file.text()), merchantId || undefined); setImportPreview(validation); const batch = await createImportBatch({ merchant_id: merchantId || undefined, file_name: file.name, import_mode: "database_preview", total_rows: validation.length, valid_rows: validation.filter((row) => row.status === "valid").length, invalid_rows: validation.filter((row) => row.status === "invalid").length }); setLastBatchId(String(batch.id || "")); await saveImportPreviewRows(String(batch.id), validation); setMessage(isArabic ? "تم حفظ معاينة الاستيراد كصفوف حقيقية في قاعدة البيانات." : "Import preview rows were saved as real database rows."); await load(); } catch (error) { console.warn("Import preview failed:", error); setMessage(isArabic ? "تعذر حفظ معاينة الاستيراد. تأكد من migration وصلاحيات الأدمن." : "Could not save import preview. Confirm migration and admin permissions."); } finally { setBusy(false); } }
  async function commitImport() { if (!lastBatchId) return; await commitValidImportRows(lastBatchId); setMessage(isArabic ? "تم اعتماد صفوف الاستيراد الصالحة." : "Valid import rows were committed."); }
  if (isFinanceSection(id)) return <AdminFinanceOperationsCenter isArabic={isArabic} activeSection={financeSection} orders={orders} merchants={merchants} financeSummary={null} financeSummarySource="derived" onRefresh={onRefresh} onNavigate={(target) => { if (isFinanceSection(target)) setFinanceSection(target); }} />;
  return <section className="dn-ops-layer" dir={isArabic ? "rtl" : "ltr"}><header><div><span>{t("organized_layer", isArabic)}</span><h1>{title}</h1><p>{t("organized_text", isArabic)}</p></div><AdminPdfExportButton payload={tablePdf(isArabic, title, dataSourceText, rows)} /></header><div className={`dn-ops-message ${source === "db" ? "is-db" : "is-warning"}`}><Database className="inline h-4 w-4" /> {dataSourceText}{message ? ` · ${message}` : ""}</div><div className="dn-ops-filters"><select value={merchantId} onChange={(event) => setMerchantId(event.target.value)}><option value="">{t("all_merchants", isArabic)}</option>{merchants.map((merchant) => <option key={merchant.id} value={merchant.id}>{merchant.trade_name || merchant.owner_name || merchant.merchant_code || merchant.id}</option>)}</select><button type="button" onClick={() => void load()}><RefreshCw className="inline h-4 w-4" /> {busy ? t("loading", isArabic) : t("refresh", isArabic)}</button><button type="button" onClick={() => window.print()}><Printer className="inline h-4 w-4" /> {t("print", isArabic)}</button></div>{id === "import" && <div className="dn-ops-filters"><input type="file" accept=".csv" onChange={(event) => event.target.files?.[0] && void handleCsv(event.target.files[0])} /><button type="button" disabled={!lastBatchId || busy} onClick={() => void commitImport()}>{t("import_commit", isArabic)}</button><span>{t("preview_saved", isArabic)}: {importPreview.length}</span></div>}<div className="dn-ops-kpis"><article><span>{t("rows", isArabic)}</span><strong>{totals.count}</strong></article><article><span>{t("debit", isArabic)}</span><strong>{money(totals.debit, isArabic)}</strong></article><article><span>{t("credit_amount", isArabic)}</span><strong>{money(totals.credit, isArabic)}</strong></article><article><span>{t("pending", isArabic)}</span><strong>{totals.pending}</strong></article></div><div className="dn-ops-table"><table><thead><tr><th>{t("date", isArabic)}</th><th>{t("tracking", isArabic)}</th><th>{t("type", isArabic)}</th><th>{t("debit", isArabic)}</th><th>{t("credit", isArabic)}</th><th>{t("balance", isArabic)}</th><th>{t("notes", isArabic)}</th></tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id || index)}><td>{rowDate(row)}</td><td>{rowReference(row)}</td><td>{valueLabel(rowType(row), isArabic)}</td><td>{money(rowDebit(row), isArabic)}</td><td>{money(rowCredit(row), isArabic)}</td><td>{money(rowBalance(row), isArabic)}</td><td>{noteLabel(rowNotes(row), isArabic)}</td></tr>)}</tbody></table>{!rows.length && <div className="dn-ops-empty"><FileText className="inline h-4 w-4" /> {t("no_rows", isArabic)}</div>}</div></section>;
}
