import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Pause, Pin, Play, RotateCcw, Truck, Wallet } from "lucide-react";
import type { Merchant } from "../../types";
import type { FinanceSummary } from "../../lib/adminData";
import { deriveCommandMetrics } from "../../data/adminCommandExpansion";

type Props = { isArabic: boolean; orders: any[]; merchants: Merchant[]; financeSummary?: FinanceSummary | null; sectionTitle?: string };
type Insight = { icon: typeof AlertTriangle; severity: string; tone: string; title: string; message: string; metric?: string };
function amount(value: unknown) { return `${Number(value || 0).toFixed(2)} AED`; }
function norm(value: unknown) { return String(value || "").toLowerCase().replace(/[_-]/g, " "); }
export default function KhalifaGuidanceFeed({ isArabic, orders, merchants, financeSummary, sectionTitle }: Props) {
  const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); const [pinned, setPinned] = useState(false);
  const metrics = useMemo(() => deriveCommandMetrics(orders, merchants, financeSummary), [orders, merchants, financeSummary]);
  const today = new Date().toISOString().slice(0, 10); const todayOrders = orders.filter((o) => String(o.created_at || "").slice(0, 10) === today).length; const returned = orders.filter((o) => norm(o.status).includes("return")).length; const pending = orders.filter((o) => /pending|review|confirm/.test(norm(o.status))).length; const sectionPrefix = sectionTitle ? (isArabic ? `قسم ${sectionTitle}: ` : `${sectionTitle}: `) : "";
  const insights = useMemo<Insight[]>(() => [
    pending > 0 && { icon: AlertTriangle, severity: isArabic ? "عاجل" : "Urgent", tone: "gold", title: isArabic ? "قرار تشغيلي مطلوب" : "Operational decision needed", metric: String(pending), message: isArabic ? `${sectionPrefix}${pending} طلب يحتاج مراجعة قبل التحريك. ابدأ بالطلبات الأقدم ثم الأعلى قيمة.` : `${sectionPrefix}${pending} orders need review before dispatch. Start with oldest and highest-value orders.` },
    metrics.unassigned > 0 && { icon: Truck, severity: isArabic ? "توزيع" : "Dispatch", tone: "blue", title: isArabic ? "فجوة مناديب" : "Driver assignment gap", metric: String(metrics.unassigned), message: isArabic ? `${metrics.unassigned} طلب نشط بدون مندوب. افتح التوزيع وعيّن أقرب سيارة لتقليل التأخير.` : `${metrics.unassigned} active orders have no assigned driver. Assign the nearest vehicle to reduce delays.` },
    Number(metrics.codPending) > 0 && { icon: Wallet, severity: isArabic ? "تحصيل" : "Collection", tone: "gold", title: isArabic ? "تحصيل COD معلق" : "Pending COD collection", metric: amount(metrics.codPending), message: isArabic ? `يوجد COD معلق بقيمة ${amount(metrics.codPending)}. راجع المناديب قبل إغلاق اليوم.` : `Pending COD is ${amount(metrics.codPending)}. Reconcile drivers before day close.` },
    returned > 0 && { icon: RotateCcw, severity: isArabic ? "متابعة" : "Follow-up", tone: "gold", title: isArabic ? "طلبات راجعة" : "Returned orders", metric: String(returned), message: isArabic ? `${returned} طلب راجع يحتاج سبب إغلاق واضح وملاحظة للتاجر.` : `${returned} returned orders need clear closure reasons and merchant notes.` },
    { icon: Clock3, severity: isArabic ? "اليوم" : "Today", tone: "blue", title: isArabic ? "ملخص اليوم" : "Today snapshot", metric: String(todayOrders), message: isArabic ? `${todayOrders} طلب جديد اليوم، ${metrics.active} نشط، و${metrics.delivered} تم تسليمه.` : `${todayOrders} new orders today, ${metrics.active} active, and ${metrics.delivered} delivered.` },
    { icon: Wallet, severity: isArabic ? "مالية" : "Finance", tone: metrics.breakEvenStatus === "positive" ? "blue" : "rose", title: isArabic ? "كسر التشغيل" : "Break-even watch", metric: amount(metrics.netEstimate), message: isArabic ? `صافي التشغيل التقديري ${amount(metrics.netEstimate)}. متوسط دخل الطلب ${amount(metrics.averageOrderRevenue)} ونسبة COD ${metrics.codRatio.toFixed(1)}%.` : `Estimated operating net is ${amount(metrics.netEstimate)}. Average order revenue is ${amount(metrics.averageOrderRevenue)} and COD ratio is ${metrics.codRatio.toFixed(1)}%.` },
    metrics.bestRegionId !== "all" && { icon: CheckCircle2, severity: isArabic ? "منطقة" : "Region", tone: "blue", title: isArabic ? "أفضل منطقة نشاط" : "Top active region", metric: String(metrics.bestRegionCount), message: isArabic ? `أعلى نشاط حالي في ${metrics.bestRegionId} بعدد ${metrics.bestRegionCount} طلب. استخدم فلتر الخريطة لمتابعتها.` : `Top activity is in ${metrics.bestRegionId} with ${metrics.bestRegionCount} orders. Use the map filter to monitor it.` },
  ].filter(Boolean) as Insight[], [isArabic, pending, returned, todayOrders, metrics, sectionPrefix]);
  const visibleInsights = insights.length ? insights : [{ icon: CheckCircle2, severity: isArabic ? "معلومة" : "Info", tone: "blue", title: isArabic ? "العمليات مستقرة" : "Operations stable", metric: "OK", message: isArabic ? "لا توجد تنبيهات عاجلة الآن. خليفة يراقب التوزيع والتحصيل والطلبات الجديدة." : "No urgent alerts right now. Khalifa is watching dispatch, collections, and new orders." }];
  const active = visibleInsights[index % visibleInsights.length]; const Icon = active.icon;
  useEffect(() => { setIndex(0); setPaused(false); setPinned(false); }, [sectionTitle, orders.length, merchants.length]);
  useEffect(() => { if (paused || pinned || visibleInsights.length <= 1) return; const timer = window.setInterval(() => setIndex((current) => (current + 1) % visibleInsights.length), 5200); return () => window.clearInterval(timer); }, [paused, pinned, visibleInsights.length]);
  const next = () => setIndex((current) => (current + 1) % visibleInsights.length); const previous = () => setIndex((current) => (current - 1 + visibleInsights.length) % visibleInsights.length);
  return <section className="dn-khalifa-feed dn-khalifa-rotator" aria-label={isArabic ? "تغذية خليفة" : "Khalifa Feed"}><header><span>{isArabic ? "خليفة مباشر" : "Live Khalifa"}</span><strong>{sectionTitle || (isArabic ? "تنبيهات وإرشادات" : "Notifications & Guidance")}</strong></header><article key={`${active.title}-${index}`} className={`dn-khalifa-current is-${active.tone}`}><div className="dn-khalifa-feed-icon"><Icon className="h-5 w-5" /></div><div className="dn-khalifa-current-body"><div className="dn-khalifa-current-top"><strong>{active.title}</strong><span>{active.severity}</span></div><p>{active.message}</p>{active.metric && <b className="dn-khalifa-current-metric">{active.metric}</b>}</div></article><div className="dn-khalifa-rotator-controls"><button type="button" onClick={previous} aria-label={isArabic ? "السابق" : "Previous"}><ChevronRight className="h-4 w-4" /></button><button type="button" onClick={() => setPaused((value) => !value)}>{paused ? <Play className="h-4 w-4" /> : <Pause className="h-4 w-4" />}</button><button type="button" onClick={() => setPinned((value) => !value)} className={pinned ? "is-active" : ""}><Pin className="h-4 w-4" /></button><button type="button" onClick={next} aria-label={isArabic ? "التالي" : "Next"}><ChevronLeft className="h-4 w-4" /></button><span>{index + 1} / {visibleInsights.length}</span></div></section>;
}
